### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by sherakama**
Change from packagist.org to packages.drupal.org

### CODE REVIEW

**Comment by jbickar** [comment]
```
% composer update

                                                                    
  [Seld\JsonLint\ParsingException]                                  
  "./composer.json" does not contain valid JSON                     
  Parse error on line 91:                                           
  ...ion": "^8.1.1",    },    "require-dev"                         
  ---------------------^                                            
  Expected: 'STRING' - It appears you have an extra trailing comma 
```

**Comment by sherakama** [comment]
Distracted by shiny things. Fixt.

**Comment by jbickar** [comment]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drupal/panopoly_widgets ^8.2.0 exists as drupal/panopoly_widgets[dev-2.x, 2.x-dev] but these are rejected by your constraint.
```

etc.

**Comment by jbickar** [comment]
Same error on `composer update`:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package drupal/radix_layouts ^8.3.0 exists as drupal/radix_layouts[dev-3.x, 3.x-dev, 3.0.0-rc1] but these are rejected by your constraint.
```

and 30 more similar problems.

**Comment by sherakama** [comment]
Seems to be a cache issue.
I used the older syntax from the previous packagist server for those. 
Im currently updating to the d.o one. The syntax changed... Not sure why.

**Pull request merged**
